version: '3.8'
services:

  #PHP Service
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      DB_HOST: db:3306
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  #MySQL Service
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bvk_mvc
      MYSQL_USER: admincha
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/dbdata/:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local